//
//  File1.swift
//  PerfectList
//
//  Created by Aleksei Petukhov on 09/04/16.
//  Copyright © 2016 PekkiPo. All rights reserved.
//

import Foundation
/*
var backuparray = [
    CatalogItem(itemId:"CatalogVegetables",itemname:NSLocalizedString("vegetables", comment: ""),itemimage:UIImage(named: "icvegetables")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"ictomatoes",itemname:NSLocalizedString("tomatoes", comment: ""),itemimage:UIImage(named: "ictomatoes")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCucumbers",itemname:NSLocalizedString("cucumbers", comment: ""),itemimage:UIImage(named: "iccucumbers")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBrocolli",itemname:NSLocalizedString("brocolli", comment: ""),itemimage:UIImage(named: "icbroccoli")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCarrot",itemname:NSLocalizedString("carrot", comment: ""),itemimage:UIImage(named: "iccarrot")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogLettuce",itemname:NSLocalizedString("lettuce", comment: ""),itemimage:UIImage(named: "icsalad")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCabbage",itemname:NSLocalizedString("cabbage", comment: ""),itemimage:UIImage(named: "iccabbage")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMushrooms",itemname:NSLocalizedString("mushrooms", comment: ""),itemimage:UIImage(named: "icmushrooms")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogOnion",itemname:NSLocalizedString("onion", comment: ""),itemimage:UIImage(named: "iconion")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPotato",itemname:NSLocalizedString("potato", comment: ""),itemimage:UIImage(named: "icpotato")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSpinach",itemname:NSLocalizedString("spinach", comment: ""),itemimage:UIImage(named: "icspinage")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogEggplant",itemname:NSLocalizedString("eggplant", comment: ""),itemimage:UIImage(named: "iceggplant")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPumpkin",itemname:NSLocalizedString("pumpkin", comment: ""),itemimage:UIImage(named: "icpumpkin")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogRadish",itemname:NSLocalizedString("radish", comment: ""),itemimage:UIImage(named: "icradish")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogGarlic",itemname:NSLocalizedString("garlic", comment: ""),itemimage:UIImage(named: "icgarlic")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogGreenBeans",itemname:NSLocalizedString("greenbeans", comment: ""),itemimage:UIImage(named: "icgreenbeans")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBellPepper",itemname:NSLocalizedString("bellpepper", comment: ""),itemimage:UIImage(named: "icpepper")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCorn",itemname:NSLocalizedString("corn", comment: ""),itemimage:UIImage(named: "iccorn")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCelery",itemname:NSLocalizedString("celery", comment: ""),itemimage:UIImage(named: "iccelery")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBeans",itemname:NSLocalizedString("beans", comment: ""),itemimage:UIImage(named: "icbeans")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogAsparagus",itemname:NSLocalizedString("asparagus", comment: ""),itemimage:UIImage(named: "icasparagus")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBeetroot",itemname:NSLocalizedString("beetroot", comment: ""),itemimage:UIImage(named: "icbeetroot")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCauliflower",itemname:NSLocalizedString("cauliflower", comment: ""),itemimage:UIImage(named: "iccauliflower")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCherryTomatoes",itemname:NSLocalizedString("cherrytomatoes", comment: ""),itemimage:UIImage(named: "iccherrytomatoes")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogChillies",itemname:NSLocalizedString("chillies", comment: ""),itemimage:UIImage(named: "icchillies")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogCilantro",itemname:NSLocalizedString("cilantro", comment: ""),itemimage:UIImage(named: "iccilantro")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogZucchini",itemname:NSLocalizedString("zucchini", comment: ""),itemimage:UIImage(named: "iczucchini")!,itemcategory:catalogcategories[1], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogFruits",itemname:NSLocalizedString("fruits", comment: ""),itemimage:UIImage(named: "icfruits")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogApples",itemname:NSLocalizedString("apples", comment: ""),itemimage:UIImage(named: "icapples")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogOranges",itemname:NSLocalizedString("oranges", comment: ""),itemimage:UIImage(named: "icoranges")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogLemons",itemname:NSLocalizedString("lemons", comment: ""),itemimage:UIImage(named: "iclemons")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogLimes",itemname:NSLocalizedString("limes", comment: ""),itemimage:UIImage(named: "iclimes")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBananas",itemname:NSLocalizedString("bananas", comment: ""),itemimage:UIImage(named: "icbananas")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCherries",itemname:NSLocalizedString("cherries", comment: ""),itemimage:UIImage(named: "iccherries")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogGrapefruits",itemname:NSLocalizedString("grapefruits", comment: ""),itemimage:UIImage(named: "icgrapefruits")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogGrapes",itemname:NSLocalizedString("grapes", comment: ""),itemimage:UIImage(named: "icgrapes")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogKiwi",itemname:NSLocalizedString("kiwi", comment: ""),itemimage:UIImage(named: "ickiwi")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogTangerines",itemname:NSLocalizedString("tangerines", comment: ""),itemimage:UIImage(named: "ictangerines")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMango",itemname:NSLocalizedString("mango", comment: ""),itemimage:UIImage(named: "icmango")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogAvocado",itemname:NSLocalizedString("avocado", comment: ""),itemimage:UIImage(named: "icavocado")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMelons",itemname:NSLocalizedString("melons", comment: ""),itemimage:UIImage(named: "icmelons")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogStrawberries",itemname:NSLocalizedString("strawberries", comment: ""),itemimage:UIImage(named: "icstrawberries")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBlueberries",itemname:NSLocalizedString("blueberries", comment: ""),itemimage:UIImage(named: "icblueberry")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogRaspberries",itemname:NSLocalizedString("raspberries", comment: ""),itemimage:UIImage(named: "icraspberry")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBlackberries",itemname:NSLocalizedString("blackberries", comment: ""),itemimage:UIImage(named: "icblackberry")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogWatermelon",itemname:NSLocalizedString("watermelon", comment: ""),itemimage:UIImage(named: "icwatermelon")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPeaches",itemname:NSLocalizedString("peaches", comment: ""),itemimage:UIImage(named: "icpeaches")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPears",itemname:NSLocalizedString("pears", comment: ""),itemimage:UIImage(named: "icpears")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPineapples",itemname:NSLocalizedString("pineapples", comment: ""),itemimage:UIImage(named: "icpineapples")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogNectarines",itemname:NSLocalizedString("nectarines", comment: ""),itemimage:UIImage(named: "icnektarines")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPlums",itemname:NSLocalizedString("plums", comment: ""),itemimage:UIImage(named: "icplums")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPapaya",itemname:NSLocalizedString("papaya", comment: ""),itemimage:UIImage(named: "icpapaya")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFigs",itemname:NSLocalizedString("figs", comment: ""),itemimage:UIImage(named: "icfigs")!,itemcategory:catalogcategories[2], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogDairy",itemname:NSLocalizedString("dairy", comment: ""),itemimage:UIImage(named: "icdairy")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMilk",itemname:NSLocalizedString("milk", comment: ""),itemimage:UIImage(named: "icmilk")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogButter",itemname:NSLocalizedString("butter", comment: ""),itemimage:UIImage(named: "icbutter")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCheese",itemname:NSLocalizedString("cheese", comment: ""),itemimage:UIImage(named: "iccheese")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCream",itemname:NSLocalizedString("cream", comment: ""),itemimage:UIImage(named: "iccream")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCreamcheese",itemname:NSLocalizedString("creamcheese", comment: ""),itemimage:UIImage(named: "iccreamcheese")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogEggs",itemname:NSLocalizedString("eggs", comment: ""),itemimage:UIImage(named: "iceggs")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFeta",itemname:NSLocalizedString("feta", comment: ""),itemimage:UIImage(named: "icfeta")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogParmesan",itemname:NSLocalizedString("parmesan", comment: ""),itemimage:UIImage(named: "icparmesan")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMargarine",itemname:NSLocalizedString("margarine", comment: ""),itemimage:UIImage(named: "icmargarine")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMascarpone",itemname:NSLocalizedString("mascarpone", comment: ""),itemimage:UIImage(named: "icmascarpone")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMozarella",itemname:NSLocalizedString("mozarella", comment: ""),itemimage:UIImage(named: "icmozarella")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogRicotta",itemname:NSLocalizedString("ricotta", comment: ""),itemimage:UIImage(named: "icricotta")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSourcream",itemname:NSLocalizedString("sourcream", comment: ""),itemimage:UIImage(named: "icsourcream")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSoymilk",itemname:NSLocalizedString("soymilk", comment: ""),itemimage:UIImage(named: "icsoymilk")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogYogurt",itemname:NSLocalizedString("yogurt", comment: ""),itemimage:UIImage(named: "icyogurt")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSchreddedcheese",itemname:NSLocalizedString("schreddedcheese", comment: ""),itemimage:UIImage(named: "icgratedcheese")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPudding",itemname:NSLocalizedString("pudding", comment: ""),itemimage:UIImage(named: "icpuding")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDrinkingyogurt",itemname:NSLocalizedString("drinkingyougurt", comment: ""),itemimage:UIImage(named: "icdrinkingyogurt")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCottagecheese",itemname:NSLocalizedString("cottagecheese", comment: ""),itemimage:UIImage(named: "iccottagecheese")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogKefir",itemname:NSLocalizedString("kefir", comment: ""),itemimage:UIImage(named: "ickefir")!,itemcategory:catalogcategories[3], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogMeat",itemname:NSLocalizedString("meat", comment: ""),itemimage:UIImage(named: "icmeat")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBeef",itemname:NSLocalizedString("beef", comment: ""),itemimage:UIImage(named: "icbeef")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogChicken",itemname:NSLocalizedString("chicken", comment: ""),itemimage:UIImage(named: "icchicken2")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogGroundbeef",itemname:NSLocalizedString("groundbeef", comment: ""),itemimage:UIImage(named: "icgroundbeef")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSteak",itemname:NSLocalizedString("steak", comment: ""),itemimage:UIImage(named: "icsteak")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogTurkey",itemname:NSLocalizedString("turkey", comment: ""),itemimage:UIImage(named: "icturkey")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPork",itemname:NSLocalizedString("pork", comment: ""),itemimage:UIImage(named: "icpork")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPorkchops",itemname:NSLocalizedString("porkchops", comment: ""),itemimage:UIImage(named: "icporkchop")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSausages",itemname:NSLocalizedString("sausages", comment: ""),itemimage:UIImage(named: "icsausages")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDuck",itemname:NSLocalizedString("duck", comment: ""),itemimage:UIImage(named: "icduck")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBacon",itemname:NSLocalizedString("bacon", comment: ""),itemimage:UIImage(named: "icbacon")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogChickenbreast",itemname:NSLocalizedString("chickenbreast", comment: ""),itemimage:UIImage(named: "icchickenbreast")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogHam",itemname:NSLocalizedString("ham", comment: ""),itemimage:UIImage(named: "ickolbasa")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogProsciutto",itemname:NSLocalizedString("prosciutto", comment: ""),itemimage:UIImage(named: "icprosciutto")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSalami",itemname:NSLocalizedString("salami", comment: ""),itemimage:UIImage(named: "icsalami")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogVeal",itemname:NSLocalizedString("veal", comment: ""),itemimage:UIImage(named: "icveal")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBarbeque",itemname:NSLocalizedString("barbeque", comment: ""),itemimage:UIImage(named: "icbbq")!,itemcategory:catalogcategories[4], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogSeafood",itemname:NSLocalizedString("seafood", comment: ""),itemimage:UIImage(named: "icseafood")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogAnchovies",itemname:NSLocalizedString("anchovies", comment: ""),itemimage:UIImage(named: "icanchovies")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFish",itemname:NSLocalizedString("fish", comment: ""),itemimage:UIImage(named: "icfish")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSalmon",itemname:NSLocalizedString("salmon", comment: ""),itemimage:UIImage(named: "icsalmon")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogLobsters",itemname:NSLocalizedString("lobsters", comment: ""),itemimage:UIImage(named: "iclobsters")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSchrimps",itemname:NSLocalizedString("schrimps", comment: ""),itemimage:UIImage(named: "icshrimps")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogOysters",itemname:NSLocalizedString("oysters", comment: ""),itemimage:UIImage(named: "icoysters")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogTuna",itemname:NSLocalizedString("tuna", comment: ""),itemimage:UIImage(named: "ictuna")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogClams",itemname:NSLocalizedString("clams", comment: ""),itemimage:UIImage(named: "icclams")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogScallops",itemname:NSLocalizedString("scallops", comment: ""),itemimage:UIImage(named: "icscallops")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCodfish",itemname:NSLocalizedString("codfish", comment: ""),itemimage:UIImage(named: "iccodfish")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPinksalmon",itemname:NSLocalizedString("pinksalmon", comment: ""),itemimage:UIImage(named: "icpinksalmon")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSprats",itemname:NSLocalizedString("sprats", comment: ""),itemimage:UIImage(named: "icsprats")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogHerring",itemname:NSLocalizedString("herring", comment: ""),itemimage:UIImage(named: "icherring")!,itemcategory:catalogcategories[5], itemischecked:false, itemaddedid: ""),
    
    
    
    CatalogItem(itemId:"CatalogBread",itemname:NSLocalizedString("bread", comment: ""),itemimage:UIImage(named: "icbread")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"Catalogbreadrolls",itemname:NSLocalizedString("breadrolls", comment: ""),itemimage:UIImage(named: "icbreadrolls")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogHamburgerbuns",itemname:NSLocalizedString("hamburgerbuns", comment: ""),itemimage:UIImage(named: "icburgerbuns")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBagels",itemname:NSLocalizedString("bagels", comment: ""),itemimage:UIImage(named: "icbagels")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPie",itemname:NSLocalizedString("pie", comment: ""),itemimage:UIImage(named: "icpie")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDarkbread",itemname:NSLocalizedString("darkbread", comment: ""),itemimage:UIImage(named: "ichleb")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCookies",itemname:NSLocalizedString("cookies", comment: ""),itemimage:UIImage(named: "iccookies")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCakes",itemname:NSLocalizedString("cakes", comment: ""),itemimage:UIImage(named: "iccake")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogWaffels",itemname:NSLocalizedString("waffles", comment: ""),itemimage:UIImage(named: "icwaffles")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPretzels",itemname:NSLocalizedString("pretzels", comment: ""),itemimage:UIImage(named: "icpretzels")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCroissants",itemname:NSLocalizedString("croissants", comment: ""),itemimage:UIImage(named: "iccroissants")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBiscuits",itemname:NSLocalizedString("biscuits", comment: ""),itemimage:UIImage(named: "icbiscuit")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCrispbread",itemname:NSLocalizedString("crispbread", comment: ""),itemimage:UIImage(named: "iccrispbread")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMuffins",itemname:NSLocalizedString("muffins", comment: ""),itemimage:UIImage(named: "icmuffin")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogToasts",itemname:NSLocalizedString("toasts", comment: ""),itemimage:UIImage(named: "ictoasts")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPizzadough",itemname:NSLocalizedString("pizzadough", comment: ""),itemimage:UIImage(named: "icpizzadough")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSlicedbread",itemname:NSLocalizedString("slicedbread", comment: ""),itemimage:UIImage(named: "icslicedbread")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogTortillas",itemname:NSLocalizedString("tortillas", comment: ""),itemimage:UIImage(named: "ictortillas")!,itemcategory:catalogcategories[6], itemischecked:false, itemaddedid: ""),
    
    
    CatalogItem(itemId:"CatalogSnacks",itemname:NSLocalizedString("snacks", comment: ""),itemimage:UIImage(named: "icsnacks")!,itemcategory:catalogcategories[7], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogChips",itemname:NSLocalizedString("chips", comment: ""),itemimage:UIImage(named: "icchips")!,itemcategory:catalogcategories[7], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDriedfruits",itemname:NSLocalizedString("driedfruits", comment: ""),itemimage:UIImage(named: "icdriedfruits")!,itemcategory:catalogcategories[7], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCrackers",itemname:NSLocalizedString("crackers", comment: ""),itemimage:UIImage(named: "iccrackers")!,itemcategory:catalogcategories[7], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogNachoes",itemname:NSLocalizedString("nachoes", comment: ""),itemimage:UIImage(named: "icnachos")!,itemcategory:catalogcategories[7], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPopcorn",itemname:NSLocalizedString("popcorn", comment: ""),itemimage:UIImage(named: "icpopcorn")!,itemcategory:catalogcategories[7], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPeanuts",itemname:NSLocalizedString("peanuts", comment: ""),itemimage:UIImage(named: "icpeanuts")!,itemcategory:catalogcategories[7], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogNuts",itemname:NSLocalizedString("nuts", comment: ""),itemimage:UIImage(named: "icnuts")!,itemcategory:catalogcategories[7], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPistachios",itemname:NSLocalizedString("pistachios", comment: ""),itemimage:UIImage(named: "icpistachos")!,itemcategory:catalogcategories[7], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCahsews",itemname:NSLocalizedString("cashews", comment: ""),itemimage:UIImage(named: "iccashews")!,itemcategory:catalogcategories[7], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogGreenolives",itemname:NSLocalizedString("greenolives", comment: ""),itemimage:UIImage(named: "icolives")!,itemcategory:catalogcategories[7], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBlackolives",itemname:NSLocalizedString("blackolives", comment: ""),itemimage:UIImage(named: "icblackolives")!,itemcategory:catalogcategories[7], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogBeverages",itemname:NSLocalizedString("beverages", comment: ""),itemimage:UIImage(named: "icbeverages")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogWater",itemname:NSLocalizedString("water", comment: ""),itemimage:UIImage(named: "icwater")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMineralwater",itemname:NSLocalizedString("mineralwater", comment: ""),itemimage:UIImage(named: "icmineralwater")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogJuice",itemname:NSLocalizedString("juice", comment: ""),itemimage:UIImage(named: "icjuice")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogOrangejuice",itemname:NSLocalizedString("orangejuice", comment: ""),itemimage:UIImage(named: "icorangejuice")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogApplejuice",itemname:NSLocalizedString("applejuice", comment: ""),itemimage:UIImage(named: "icapplejuice")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCherryjuice",itemname:NSLocalizedString("cherryjuice", comment: ""),itemimage:UIImage(named: "iccherryjuice")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogGrapejuice",itemname:NSLocalizedString("grapejuice", comment: ""),itemimage:UIImage(named: "icgrapejuice")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogLemonjuice",itemname:NSLocalizedString("lemonjuice", comment: ""),itemimage:UIImage(named: "iclemonjuice")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCocacola",itemname:NSLocalizedString("cocacola", comment: ""),itemimage:UIImage(named: "iccocacola")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPepsi",itemname:NSLocalizedString("pepsi", comment: ""),itemimage:UIImage(named: "icpepsi")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogLemonade",itemname:NSLocalizedString("lemonade", comment: ""),itemimage:UIImage(named: "iclemonade")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDrpepper",itemname:NSLocalizedString("drpepper", comment: ""),itemimage:UIImage(named: "icdrpepper")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"Catalog5lwater",itemname:NSLocalizedString("5lwater", comment: ""),itemimage:UIImage(named: "ic5lwater")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogTea",itemname:NSLocalizedString("tea", comment: ""),itemimage:UIImage(named: "ictea")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCoffee",itemname:NSLocalizedString("coffee", comment: ""),itemimage:UIImage(named: "iccoffee")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogIcetea",itemname:NSLocalizedString("icetea", comment: ""),itemimage:UIImage(named: "icicetea")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCider",itemname:NSLocalizedString("cider", comment: ""),itemimage:UIImage(named: "iccider")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogHotchocolade",itemname:NSLocalizedString("hotchocolate", comment: ""),itemimage:UIImage(named: "ichotchocolate")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogEnergydrink",itemname:NSLocalizedString("energydrink", comment: ""),itemimage:UIImage(named: "icenergy")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSportdrink",itemname:NSLocalizedString("sportdrink", comment: ""),itemimage:UIImage(named: "icsportdrink")!,itemcategory:catalogcategories[8], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogAlcohol",itemname:NSLocalizedString("alcohol", comment: ""),itemimage:UIImage(named: "icalcohol")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBeer",itemname:NSLocalizedString("beer", comment: ""),itemimage:UIImage(named: "icbeer")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogChampagne",itemname:NSLocalizedString("champagne", comment: ""),itemimage:UIImage(named: "icchampagne")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogVodka",itemname:NSLocalizedString("vodka", comment: ""),itemimage:UIImage(named: "icvodka")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogRedrum",itemname:NSLocalizedString("redrum", comment: ""),itemimage:UIImage(named: "icredrum")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogWhiterum",itemname:NSLocalizedString("whiterum", comment: ""),itemimage:UIImage(named: "icwhiterum")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogTequila",itemname:NSLocalizedString("tequila", comment: ""),itemimage:UIImage(named: "ictequila")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogWhiskey",itemname:NSLocalizedString("whiskey", comment: ""),itemimage:UIImage(named: "icwhiskey")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogGin",itemname:NSLocalizedString("gin", comment: ""),itemimage:UIImage(named: "icgin")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogTonic",itemname:NSLocalizedString("tonic", comment: ""),itemimage:UIImage(named: "ictonic")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogProsecco",itemname:NSLocalizedString("prosecco", comment: ""),itemimage:UIImage(named: "icprosecco")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogWine",itemname:NSLocalizedString("justwine", comment: ""),itemimage:UIImage(named: "icredwine")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogRedwine",itemname:NSLocalizedString("redwine", comment: ""),itemimage:UIImage(named: "icredwine")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogWhitewine",itemname:NSLocalizedString("whitewine", comment: ""),itemimage:UIImage(named: "icwhitewine")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPinkwine",itemname:NSLocalizedString("pinkwine", comment: ""),itemimage:UIImage(named: "icpinkwine")!,itemcategory:catalogcategories[9], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogCereals",itemname:NSLocalizedString("cereals", comment: ""),itemimage:UIImage(named: "iccereals")!,itemcategory:catalogcategories[10], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogHoney",itemname:NSLocalizedString("honey", comment: ""),itemimage:UIImage(named: "ichoney")!,itemcategory:catalogcategories[10], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogOatmeal",itemname:NSLocalizedString("oatmeal", comment: ""),itemimage:UIImage(named: "icoatmeal")!,itemcategory:catalogcategories[10], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCornflakes",itemname:NSLocalizedString("cornflakes", comment: ""),itemimage:UIImage(named: "iccornflakes")!,itemcategory:catalogcategories[10], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogNesquick",itemname:NSLocalizedString("nesquick", comment: ""),itemimage:UIImage(named: "icnesquick")!,itemcategory:catalogcategories[10], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogGranola",itemname:NSLocalizedString("granola", comment: ""),itemimage:UIImage(named: "icgranola")!,itemcategory:catalogcategories[10], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogJam",itemname:NSLocalizedString("jam", comment: ""),itemimage:UIImage(named: "icjam")!,itemcategory:catalogcategories[10], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMuesli",itemname:NSLocalizedString("muesli", comment: ""),itemimage:UIImage(named: "icmuesli")!,itemcategory:catalogcategories[10], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPorridge",itemname:NSLocalizedString("porridge", comment: ""),itemimage:UIImage(named: "icporridge")!,itemcategory:catalogcategories[10], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPancakes",itemname:NSLocalizedString("pancakes", comment: ""),itemimage:UIImage(named: "icpancakes")!,itemcategory:catalogcategories[10], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogSweets",itemname:NSLocalizedString("sweets", comment: ""),itemimage:UIImage(named: "icsweets")!,itemcategory:catalogcategories[11], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogChocolate",itemname:NSLocalizedString("chocolate", comment: ""),itemimage:UIImage(named: "icchocolate")!,itemcategory:catalogcategories[11], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCandy",itemname:NSLocalizedString("candy", comment: ""),itemimage:UIImage(named: "iccandy")!,itemcategory:catalogcategories[11], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogChewinggum",itemname:NSLocalizedString("chewinggum", comment: ""),itemimage:UIImage(named: "icchewinggum")!,itemcategory:catalogcategories[11], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogNougat",itemname:NSLocalizedString("nougatcreme", comment: ""),itemimage:UIImage(named: "icnougatcreme")!,itemcategory:catalogcategories[11], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogChocolatecream",itemname:NSLocalizedString("chocolatecream", comment: ""),itemimage:UIImage(named: "icchocolatecream")!,itemcategory:catalogcategories[11], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDessert",itemname:NSLocalizedString("dessert", comment: ""),itemimage:UIImage(named: "icdessert")!,itemcategory:catalogcategories[11], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogChristmascookies",itemname:NSLocalizedString("christmascookies", comment: ""),itemimage:UIImage(named: "icchristmascookies")!,itemcategory:catalogcategories[11], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogOil",itemname:NSLocalizedString("oil", comment: ""),itemimage:UIImage(named: "icoil")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogOliveoil",itemname:NSLocalizedString("oliveoil", comment: ""),itemimage:UIImage(named: "icoliveoil")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSpices",itemname:NSLocalizedString("spices", comment: ""),itemimage:UIImage(named: "icspices")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSalt",itemname:NSLocalizedString("salt", comment: ""),itemimage:UIImage(named: "icsalt")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSugar",itemname:NSLocalizedString("sugar", comment: ""),itemimage:UIImage(named: "icsugar")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPepper",itemname:NSLocalizedString("pepper", comment: ""),itemimage:UIImage(named: "icsmallpepper")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogMayonnaise",itemname:NSLocalizedString("mayonnaise", comment: ""),itemimage:UIImage(named: "icmayonnaise")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMustard",itemname:NSLocalizedString("mustard", comment: ""),itemimage:UIImage(named: "icmustard")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogKetchup",itemname:NSLocalizedString("ketchup", comment: ""),itemimage:UIImage(named: "icketchup")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSalsa",itemname:NSLocalizedString("salsa", comment: ""),itemimage:UIImage(named: "icsalsasauce")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPastasauce",itemname:NSLocalizedString("pastasauce", comment: ""),itemimage:UIImage(named: "icpastasauce")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSeasonings",itemname:NSLocalizedString("seasonings", comment: ""),itemimage:UIImage(named: "icseasonings")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSyrup",itemname:NSLocalizedString("syrup", comment: ""),itemimage:UIImage(named: "icsyrup")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSoysauce",itemname:NSLocalizedString("soysauce", comment: ""),itemimage:UIImage(named: "icsoysauce")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBrownsugar",itemname:NSLocalizedString("brownsugar", comment: ""),itemimage:UIImage(named: "icbrownsugar")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFlour",itemname:NSLocalizedString("flour", comment: ""),itemimage:UIImage(named: "icflour")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogJelly",itemname:NSLocalizedString("jelly", comment: ""),itemimage:UIImage(named: "icjelly")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPeanutbutter",itemname:NSLocalizedString("peanutbutter", comment: ""),itemimage:UIImage(named: "icpeanutbutter")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBbqsauce",itemname:NSLocalizedString("bbqsauce", comment: ""),itemimage:UIImage(named: "icbbqsauce")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBakingpowder",itemname:NSLocalizedString("bakingpowder", comment: ""),itemimage:UIImage(named: "icbakingpowder")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBalsamicvinegar",itemname:NSLocalizedString("balsamicvinegar", comment: ""),itemimage:UIImage(named: "icbalsamicvinegar")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSoda2",itemname:NSLocalizedString("soda2", comment: ""),itemimage:UIImage(named: "icsoda2")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBreadcrumbs",itemname:NSLocalizedString("breadcrumbs", comment: ""),itemimage:UIImage(named: "icbreadcrumbs")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCinnamon",itemname:NSLocalizedString("cinnamon", comment: ""),itemimage:UIImage(named: "iccinnamon")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMaplesyrup",itemname:NSLocalizedString("maplesyrup", comment: ""),itemimage:UIImage(named: "icmaplesyrup")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPaprika",itemname:NSLocalizedString("paprika", comment: ""),itemimage:UIImage(named: "icpaprika")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSaladdressing",itemname:NSLocalizedString("saladdressing", comment: ""),itemimage:UIImage(named: "icsaladdressing")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogVanilla",itemname:NSLocalizedString("vanilla", comment: ""),itemimage:UIImage(named: "icvanilla")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogYeast",itemname:NSLocalizedString("yeast", comment: ""),itemimage:UIImage(named: "icyeast")!,itemcategory:catalogcategories[12], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogCannedfood",itemname:NSLocalizedString("cannedfood", comment: ""),itemimage:UIImage(named: "iccannedfood")!,itemcategory:catalogcategories[13], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCannedbeans",itemname:NSLocalizedString("cannedbeans", comment: ""),itemimage:UIImage(named: "iccannedbeans")!,itemcategory:catalogcategories[13], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCannedcorn",itemname:NSLocalizedString("cannedcorn", comment: ""),itemimage:UIImage(named: "iccannedcorn")!,itemcategory:catalogcategories[13], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCannedfruits",itemname:NSLocalizedString("cannedfruits", comment: ""),itemimage:UIImage(named: "iccannedfruits")!,itemcategory:catalogcategories[13], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCannedfish",itemname:NSLocalizedString("cannedfish", comment: ""),itemimage:UIImage(named: "iccannedfish")!,itemcategory:catalogcategories[13], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCannedsoup",itemname:NSLocalizedString("cannedsoup", comment: ""),itemimage:UIImage(named: "iccannedsoup")!,itemcategory:catalogcategories[13], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogPastamacaroni",itemname:NSLocalizedString("pastamacaroni", comment: ""),itemimage:UIImage(named: "icpasta")!,itemcategory:catalogcategories[14], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSpaghetti",itemname:NSLocalizedString("spaghetti", comment: ""),itemimage:UIImage(named: "icspaghetti")!,itemcategory:catalogcategories[14], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogNoodles",itemname:NSLocalizedString("noodles", comment: ""),itemimage:UIImage(named: "icnoodles")!,itemcategory:catalogcategories[14], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogVermicelli",itemname:NSLocalizedString("vermicelli", comment: ""),itemimage:UIImage(named: "icvermicelli")!,itemcategory:catalogcategories[14], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogGrains",itemname:NSLocalizedString("grains", comment: ""),itemimage:UIImage(named: "icgrains")!,itemcategory:catalogcategories[15], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogRice",itemname:NSLocalizedString("rice", comment: ""),itemimage:UIImage(named: "icrice")!,itemcategory:catalogcategories[15], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBrownrice",itemname:NSLocalizedString("brownrice", comment: ""),itemimage:UIImage(named: "icbrownrice")!,itemcategory:catalogcategories[15], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCouscous",itemname:NSLocalizedString("couscous", comment: ""),itemimage:UIImage(named: "iccouscous")!,itemcategory:catalogcategories[15], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogRisottorice",itemname:NSLocalizedString("risottorice", comment: ""),itemimage:UIImage(named: "icrisotto")!,itemcategory:catalogcategories[15], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogWildrice",itemname:NSLocalizedString("wildrice", comment: ""),itemimage:UIImage(named: "icwildrice")!,itemcategory:catalogcategories[15], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogFrozengoods",itemname:NSLocalizedString("frozengoods", comment: ""),itemimage:UIImage(named: "icfrozenfood")!,itemcategory:catalogcategories[16], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogIcecream",itemname:NSLocalizedString("icecream", comment: ""),itemimage:UIImage(named: "icicecream")!,itemcategory:catalogcategories[16], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFrozenfruits",itemname:NSLocalizedString("frozenfruits", comment: ""),itemimage:UIImage(named: "icfrozenfruits")!,itemcategory:catalogcategories[16], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFrozenvegetables",itemname:NSLocalizedString("frozenvegetables", comment: ""),itemimage:UIImage(named: "icfrozenvegetables")!,itemcategory:catalogcategories[16], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPizza",itemname:NSLocalizedString("frozenpizza", comment: ""),itemimage:UIImage(named: "icfrozenpizza")!,itemcategory:catalogcategories[16], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFrozenmeals",itemname:NSLocalizedString("frozenmeals", comment: ""),itemimage:UIImage(named: "icfrozenmeals")!,itemcategory:catalogcategories[16], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFrozenfish",itemname:NSLocalizedString("frozenfish", comment: ""),itemimage:UIImage(named: "icfrozenfish")!,itemcategory:catalogcategories[16], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFrozenfries",itemname:NSLocalizedString("frozenfries", comment: ""),itemimage:UIImage(named: "icfrozenfries")!,itemcategory:catalogcategories[16], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFrozennuggets",itemname:NSLocalizedString("frozennuggets", comment: ""),itemimage:UIImage(named: "icfrozennuggets")!,itemcategory:catalogcategories[16], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFrozenpancakes",itemname:NSLocalizedString("frozenpancakes", comment: ""),itemimage:UIImage(named: "icfrozenpancakes")!,itemcategory:catalogcategories[16], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogBabyfood",itemname:NSLocalizedString("babyfood", comment: ""),itemimage:UIImage(named: "icbabyfood")!,itemcategory:catalogcategories[17], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDiapers",itemname:NSLocalizedString("diapers", comment: ""),itemimage:UIImage(named: "icdiapers")!,itemcategory:catalogcategories[17], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogWipes",itemname:NSLocalizedString("wipes", comment: ""),itemimage:UIImage(named: "icbabywipes")!,itemcategory:catalogcategories[17], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBabyshampoo",itemname:NSLocalizedString("babyshampoo", comment: ""),itemimage:UIImage(named: "icbabyshampoo")!,itemcategory:catalogcategories[17], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBabysoap",itemname:NSLocalizedString("babysoap", comment: ""),itemimage:UIImage(named: "icbabysoap")!,itemcategory:catalogcategories[17], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBabyoil",itemname:NSLocalizedString("babyoil", comment: ""),itemimage:UIImage(named: "icbabyoil")!,itemcategory:catalogcategories[17], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBabypowder",itemname:NSLocalizedString("babypowder", comment: ""),itemimage:UIImage(named: "icbabypowder")!,itemcategory:catalogcategories[17], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPacifiers",itemname:NSLocalizedString("pacifiers", comment: ""),itemimage:UIImage(named: "icpacifiers")!,itemcategory:catalogcategories[17], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogRashcream",itemname:NSLocalizedString("rashcream", comment: ""),itemimage:UIImage(named: "icrash")!,itemcategory:catalogcategories[17], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSanitizer",itemname:NSLocalizedString("sanitizer", comment: ""),itemimage:UIImage(named: "icsanitizer")!,itemcategory:catalogcategories[17], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogToddler",itemname:NSLocalizedString("toddler", comment: ""),itemimage:UIImage(named: "ictoddler")!,itemcategory:catalogcategories[17], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogDogfood",itemname:NSLocalizedString("dogfood", comment: ""),itemimage:UIImage(named: "icdogfood")!,itemcategory:catalogcategories[18], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCatfood",itemname:NSLocalizedString("catfood", comment: ""),itemimage:UIImage(named: "iccatfood")!,itemcategory:catalogcategories[18], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBirdfood",itemname:NSLocalizedString("birdfood", comment: ""),itemimage:UIImage(named: "icbirdfood")!,itemcategory:catalogcategories[18], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDogtreats",itemname:NSLocalizedString("dogtreats", comment: ""),itemimage:UIImage(named: "icdogtreats")!,itemcategory:catalogcategories[18], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCattreats",itemname:NSLocalizedString("cattreats", comment: ""),itemimage:UIImage(named: "iccattreats")!,itemcategory:catalogcategories[18], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFishfood",itemname:NSLocalizedString("fishfood", comment: ""),itemimage:UIImage(named: "icfishfood")!,itemcategory:catalogcategories[18], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCatlitter",itemname:NSLocalizedString("catlitter", comment: ""),itemimage:UIImage(named: "iccatlitter")!,itemcategory:catalogcategories[18], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogBodylotion",itemname:NSLocalizedString("bodylotion", comment: ""),itemimage:UIImage(named: "icbodylotion")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogShampoo",itemname:NSLocalizedString("shampoo", comment: ""),itemimage:UIImage(named: "icshampoo")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogHairconditioner",itemname:NSLocalizedString("hairconditioner", comment: ""),itemimage:UIImage(named: "ichairconditioner")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCondoms",itemname:NSLocalizedString("condoms", comment: ""),itemimage:UIImage(named: "iccondoms")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogLenssolution",itemname:NSLocalizedString("lenssolution", comment: ""),itemimage:UIImage(named: "iclenssolution")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCottonpads",itemname:NSLocalizedString("cottonpads", comment: ""),itemimage:UIImage(named: "iccottonpads")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDentalfloss",itemname:NSLocalizedString("dentalfloss", comment: ""),itemimage:UIImage(named: "icdentalfloss")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCottonswabs",itemname:NSLocalizedString("cottonswabs", comment: ""),itemimage:UIImage(named: "iccottonswabs")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDeodorant",itemname:NSLocalizedString("deodorant", comment: ""),itemimage:UIImage(named: "icdeodorant")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFacecream",itemname:NSLocalizedString("facecream", comment: ""),itemimage:UIImage(named: "icfacecream")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFacialtissues",itemname:NSLocalizedString("facialtissues", comment: ""),itemimage:UIImage(named: "icfacialtissues")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogToothpaste",itemname:NSLocalizedString("toothpaste", comment: ""),itemimage:UIImage(named: "ictoothpaste")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogToothbrush",itemname:NSLocalizedString("toothbrush", comment: ""),itemimage:UIImage(named: "ictoothbrush")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogHairgel",itemname:NSLocalizedString("hairgel", comment: ""),itemimage:UIImage(named: "ichairgel")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogHairspray",itemname:NSLocalizedString("hairspray", comment: ""),itemimage:UIImage(named: "ichairspray")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogHandcream",itemname:NSLocalizedString("handcream", comment: ""),itemimage:UIImage(named: "ichandcream")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMouthwash",itemname:NSLocalizedString("mouthwash", comment: ""),itemimage:UIImage(named: "icmouthwash")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogNailpolish",itemname:NSLocalizedString("nailpolish", comment: ""),itemimage:UIImage(named: "icnailpolish")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogNailpolishremover",itemname:NSLocalizedString("nailpolishremover", comment: ""),itemimage:UIImage(named: "icnailpolishremover")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogRazor",itemname:NSLocalizedString("razor", comment: ""),itemimage:UIImage(named: "icrazor")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogRazorblades",itemname:NSLocalizedString("razorblades", comment: ""),itemimage:UIImage(named: "icrazorblades")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogShavingcream",itemname:NSLocalizedString("shavingcream", comment: ""),itemimage:UIImage(named: "icshavingcream")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogShowergel",itemname:NSLocalizedString("showergel", comment: ""),itemimage:UIImage(named: "icshowergel")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSoap",itemname:NSLocalizedString("soap", comment: ""),itemimage:UIImage(named: "icsoap")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSunscreen",itemname:NSLocalizedString("sunscreen", comment: ""),itemimage:UIImage(named: "icsunscreen")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogTampons",itemname:NSLocalizedString("tampons", comment: ""),itemimage:UIImage(named: "ictampons")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogTissues",itemname:NSLocalizedString("tissues", comment: ""),itemimage:UIImage(named: "ictissues")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogWetwipes",itemname:NSLocalizedString("wetwipes", comment: ""),itemimage:UIImage(named: "icwetwipes")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogAftershave",itemname:NSLocalizedString("aftershave", comment: ""),itemimage:UIImage(named: "icaftershave")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogMascara",itemname:NSLocalizedString("mascara", comment: ""),itemimage:UIImage(named: "icmascara")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogEyeshadow",itemname:NSLocalizedString("eyeshadow", comment: ""),itemimage:UIImage(named: "iceyeshadow")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogLipstick",itemname:NSLocalizedString("lipstick", comment: ""),itemimage:UIImage(named: "iclipstick")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCottonballs",itemname:NSLocalizedString("cottonballs", comment: ""),itemimage:UIImage(named: "iccottonballs")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogToothpicks",itemname:NSLocalizedString("toothpicks", comment: ""),itemimage:UIImage(named: "ictoothsticks")!,itemcategory:catalogcategories[19], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogMedications",itemname:NSLocalizedString("medications", comment: ""),itemimage:UIImage(named: "icmedications")!,itemcategory:catalogcategories[20], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPlasters",itemname:NSLocalizedString("plasters", comment: ""),itemimage:UIImage(named: "icplasters")!,itemcategory:catalogcategories[20], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPainreliever",itemname:NSLocalizedString("painreliever", comment: ""),itemimage:UIImage(named: "icpainrelievers")!,itemcategory:catalogcategories[20], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogVitamins",itemname:NSLocalizedString("vitamins", comment: ""),itemimage:UIImage(named: "icvitamins")!,itemcategory:catalogcategories[20], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogAntiflewtreatments",itemname:NSLocalizedString("antiflewtreatments", comment: ""),itemimage:UIImage(named: "icantiflu")!,itemcategory:catalogcategories[20], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPyretic",itemname:NSLocalizedString("pyretic", comment: ""),itemimage:UIImage(named: "icpyretic")!,itemcategory:catalogcategories[20], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogSponge",itemname:NSLocalizedString("sponge", comment: ""),itemimage:UIImage(named: "icsponge")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPapertowel",itemname:NSLocalizedString("papertowel", comment: ""),itemimage:UIImage(named: "icpapertowels")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogToiletpaper",itemname:NSLocalizedString("toiletpaper", comment: ""),itemimage:UIImage(named: "ictoiletpaper")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDisinfectant",itemname:NSLocalizedString("disinfectant", comment: ""),itemimage:UIImage(named: "icdisinfectant")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogLaundrypowder",itemname:NSLocalizedString("washingpowder", comment: ""),itemimage:UIImage(named: "iclaundrypowder")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogLaundrydetergent",itemname:NSLocalizedString("laundrydetergent", comment: ""),itemimage:UIImage(named: "iclaundrydetergent")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDishsoap",itemname:NSLocalizedString("dishsoap", comment: ""),itemimage:UIImage(named: "icdishsoap")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogWipes1",itemname:NSLocalizedString("wipes1", comment: ""),itemimage:UIImage(named: "icwipes1")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogTrahsbugs",itemname:NSLocalizedString("trashbags", comment: ""),itemimage:UIImage(named: "ictrashbags")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBucket",itemname:NSLocalizedString("bucket", comment: ""),itemimage:UIImage(named: "icbucket")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogSqueegee",itemname:NSLocalizedString("squeegee", comment: ""),itemimage:UIImage(named: "icsqueegee")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogLiquidsoap",itemname:NSLocalizedString("liquidsoap", comment: ""),itemimage:UIImage(named: "icliquidsoap")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogAluminiumfoil",itemname:NSLocalizedString("aluminiumfoil", comment: ""),itemimage:UIImage(named: "icaluminiumfoil")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBathroomcleaner",itemname:NSLocalizedString("bathroomcleaner", comment: ""),itemimage:UIImage(named: "icbathroomcleaner")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogToiletcleaner",itemname:NSLocalizedString("toiletcleaner", comment: ""),itemimage:UIImage(named: "ictoiletcleaner")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBatteries",itemname:NSLocalizedString("batteries", comment: ""),itemimage:UIImage(named: "icbatteries")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCandles",itemname:NSLocalizedString("candles", comment: ""),itemimage:UIImage(named: "iccandles")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogCharcoal",itemname:NSLocalizedString("charcoal", comment: ""),itemimage:UIImage(named: "iccharcoal")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDishwashersalt",itemname:NSLocalizedString("dishwashersalt", comment: ""),itemimage:UIImage(named: "icdishwashersalt")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDishwashertabs",itemname:NSLocalizedString("dishwashertabs", comment: ""),itemimage:UIImage(named: "icdishwashertabs")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogDishwashingliquid",itemname:NSLocalizedString("dishwashingliquid", comment: ""),itemimage:UIImage(named: "icdishliquid")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogFabricsoftener",itemname:NSLocalizedString("fabricsoftener", comment: ""),itemimage:UIImage(named: "icfabricsoftener")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogGlasscleaner",itemname:NSLocalizedString("glasscleaner", comment: ""),itemimage:UIImage(named: "icglasscleaner")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPlasticwrap",itemname:NSLocalizedString("plasticwrap", comment: ""),itemimage:UIImage(named: "icplasticwrap")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogWrappingpaper",itemname:NSLocalizedString("wrappingpaper", comment: ""),itemimage:UIImage(named: "icwrappingpaper")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogBrazier",itemname:NSLocalizedString("brazier", comment: ""),itemimage:UIImage(named: "icbrazier")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPlasticplates",itemname:NSLocalizedString("plasticplates", comment: ""),itemimage:UIImage(named: "icplasticplates")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogPlasticcups",itemname:NSLocalizedString("plasticcups", comment: ""),itemimage:UIImage(named: "icplasticcups")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogIgnition",itemname:NSLocalizedString("ignition", comment: ""),itemimage:UIImage(named: "icignition")!,itemcategory:catalogcategories[21], itemischecked:false, itemaddedid: ""),
    
    CatalogItem(itemId:"CatalogCigarettes",itemname:NSLocalizedString("cigarettes", comment: ""),itemimage:UIImage(named: "iccigarettes")!,itemcategory:catalogcategories[22], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogLighter",itemname:NSLocalizedString("lighter", comment: ""),itemimage:UIImage(named: "iclighter")!,itemcategory:catalogcategories[22], itemischecked:false, itemaddedid: ""),
    CatalogItem(itemId:"CatalogTobacco",itemname:NSLocalizedString("tobacco", comment: ""),itemimage:UIImage(named: "ictobacco")!,itemcategory:catalogcategories[22], itemischecked:false, itemaddedid: "")
    
]
*/